### ISSUE TITLE
How do I use this

### ISSUE THREAD

**Issue by pilotkid** [tuckerbuchy/ledvis#4]
Hello I was wondering on how you use this and send the audio over. There is no documentation on how to get started my Arduino is all wired up please get back to me on how to do the software portion of this. Thanks!

**Comment by tuckerbuchy** [comment]
Hey! Sorry about the poor doc its just kinda a fun project I messed with.
Im out travelling now but will do my best. I just configured my audio
settings on Ubuntu (I'm not sure about other systems ATM) to route the
output audio to an input channel. It was really straightforward. There is
some drop down menu in the audio settings that allows you to do this... I
believe it was like.. "Send audio to input" or something. Sorry about
vagueness I'm out of town without a computer

On Friday, March 13, 2015, pilotkid <notifications@github.com> wrote:

> Hello I was wondering on how you use this and send the audio over. There
> is no documentation on how to get started my Arduino is all wired up please
> get back to me on how to do the software portion of this. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tuckerbuchy/ledvis/issues/4>.
>


-- 
Tucker Buchy

Phone : (778) 989-3169
Email  : tucker.buchy@gmail.com

**Comment by pilotkid** [comment]
Sorry it took me so long to reply I never got an email saying you replied when you can would you please please please get me that info. Thanks!!

**Comment by tuckerbuchy** [comment]
Hey man, just working on a bit of a readme to walk you through it. Will be putting some work into it tomorrow.

**Comment by pilotkid** [comment]
Alright sweet thanks man you are the best!!



—

**Comment by pilotkid** [comment]
Hey man how do you send audio to the app?
